DEL /F /S /Q /AH "*.suo"
DEL /F /S /Q "*.sdf"
DEL /F /S /Q "*.opensdf"
DEL /F /S /Q "*.sdf"
DEL /F /S /Q "*.db"
RMDIR /S /Q "intermidiate"
RMDIR /S /Q "ipch"
RMDIR /S /Q ".vs"
DEL /F /S /Q "bin\*pdb"
DEL /F /S /Q "bin\*ilk"
DEL /F /S /Q "bin\*iobj"